#!/bin/bash

cd "$(dirname "$0")"

if (source python/venv/bin/activate) ; then
		echo "venv installed 👍"
else 
		cd python
		python -m venv venv 
		source venv/bin/activate
		pip install -r requirements.txt
		cd ..
fi

python3 bot.py